name: flutter_flashlight
description: A flutter plugin controlling the flash light.
version: 1.0.0
homepage: https://github.com/HomeXLabs/flutter-flashlight

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.homex.flashlight
        pluginClass: FlashlightPlugin
      ios:
        pluginClass: FlashlightPlugin